use anyhow::{Context, Result};
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

fn prompt(question: &str) -> Result<String> {
    print!("{} ", question);
    io::stdout().flush()?;
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    Ok(input.trim().to_string())
}

fn prompt_with_default(question: &str, default: &str) -> Result<String> {
    print!("{} [{}]: ", question, default);
    io::stdout().flush()?;
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let input = input.trim().to_string();
    if input.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(input)
    }
}

fn confirm(question: &str) -> Result<bool> {
    let answer = prompt(&format!("{} [Y/n]: ", question))?;
    Ok(answer.is_empty() || answer.to_lowercase() == "y" || answer.to_lowercase() == "yes")
}

pub fn run_setup() -> Result<()> {
    println!("");
    println!("=== MorphVPN Setup Wizard ===");
    println!("");

    let mode = prompt_with_default("Server or client? (server/client)", "server")?;
    let is_server = mode.to_lowercase() == "server";

    if is_server {
        setup_server()
    } else {
        setup_client()
    }
}

fn setup_server() -> Result<()> {
    println!("");
    println!("--- Server Setup ---");
    println!("");

    let name = prompt_with_default("Server name", "morphvpn-server")?;
    let bind = prompt_with_default("Bind address", "0.0.0.0:51820")?;
    let tun = prompt_with_default("TUN interface name", "tun0")?;
    let tun_ip = prompt_with_default("Tunnel IP (server side)", "10.8.0.1")?;

    let config_dir = PathBuf::from("/etc/morphvpn");
    let is_root = std::env::var("USER").unwrap_or_default() == "root";

    let target_dir = if is_root {
        config_dir.clone()
    } else {
        let home = std::env::var("HOME").context("cannot determine HOME")?;
        PathBuf::from(home).join(".morphvpn")
    };

    fs::create_dir_all(&target_dir)
        .with_context(|| format!("failed to create {}", target_dir.display()))?;

    println!("");
    println!("Config directory: {}", target_dir.display());

    println!("");
    println!("Generating server keys...");
    let _identity = crate::cert::CertIdentity::generate_cn(&name)?;

    let x25519_identity = crate::identity::generate_x25519_identity();
    let key_path = target_dir.join("server.key");
    let pub_path = target_dir.join("server.pub");
    crate::identity::write_private_key_file(&key_path, &x25519_identity.private)?;
    crate::identity::write_public_key_file(&pub_path, &x25519_identity.public)?;
    set_permissions(&key_path)?;

    println!("  Private key: {}", key_path.display());
    println!("  Public key:  {}", pub_path.display());

    let psk_hex = generate_random_hex(32);
    let psk_path = target_dir.join("server.psk");
    fs::write(&psk_path, format!("{}\n", psk_hex))?;
    set_permissions(&psk_path)?;
    println!("  PSK:         {}", psk_path.display());

    let cookie_key = generate_random_hex(32);

    let acl_path = target_dir.join("acl.toml");
    let acl_content = format!(
        r#"# MorphVPN ACL Configuration
# Add authorized clients here

# Example:
# [[clients]]
# name = "my-laptop"
# public_key = "CLIENT_PUBLIC_KEY_HEX"
# inner_ip = "10.8.0.5"
"#
    );
    fs::write(&acl_path, acl_content)?;
    println!("  ACL:         {}", acl_path.display());

    let config_path = target_dir.join("server.toml");
    let config_content = format!(
        r#"# MorphVPN Server Configuration
# Generated by morphvpn setup

[server]
bind = "{}"
private_key = "{}"
acl = "{}"
tun = "{}"
tun_ip = "{}"

[server.psk]
file = "{}"

[server.cookie]
master_key = "{}"
rotation_secs = 60

[server.tcp]
enabled = true
port = {}

[server.keepalive]
interval_secs = 15
timeout_secs = 45

[log]
format = "pretty"
level = "morphvpn=info"
"#,
        bind,
        key_path.display(),
        acl_path.display(),
        tun,
        tun_ip,
        psk_path.display(),
        cookie_key,
        bind_port(&bind) + 1,
    );
    fs::write(&config_path, config_content)?;
    println!("  Config:      {}", config_path.display());

    if is_root && confirm("Install systemd service?")? {
        let service_content = format!(
            r#"[Unit]
Description=MorphVPN Server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/morphvpn --config {} server
Restart=on-failure
RestartSec=5
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_SYS_ADMIN

[Install]
WantedBy=multi-user.target
"#,
            config_path.display()
        );
        fs::write("/etc/systemd/system/morphvpn.service", service_content)?;
        run_cmd_quiet("systemctl", &["daemon-reload"])?;
        println!("  Systemd service installed");

        if confirm("Enable and start service now?")? {
            run_cmd_quiet("systemctl", &["enable", "morphvpn"])?;
            run_cmd_quiet("systemctl", &["start", "morphvpn"])?;
            println!("  Service started!");
        }
    }

    println!("");
    println!("=== Setup Complete ===");
    println!("");
    println!("Server public key (share with clients):");
    println!("  {}", hex::encode(x25519_identity.public));
    println!("");
    println!("Next steps:");
    println!("  1. Add client public keys to {}", acl_path.display());
    println!("  2. Copy server.pub and server.psk to clients (securely!)");
    println!("  3. Client connects to: {}", bind);
    println!("");

    Ok(())
}

fn setup_client() -> Result<()> {
    println!("");
    println!("--- Client Setup ---");
    println!("");

    let server_addr = prompt("Server address (ip:port):")?;
    let server_pub_key = prompt("Server public key (hex):")?;
    let psk_hex = prompt("PSK (hex):")?;
    let tun = prompt_with_default("TUN interface name", "tun1")?;
    let tun_ip = prompt_with_default("Tunnel IP (client side)", "10.8.0.5")?;
    let gateway = prompt_with_default("Gateway (server tunnel IP)", "10.8.0.1")?;
    let _name = prompt_with_default("Client name", "morphvpn-client")?;

    let home = std::env::var("HOME").context("cannot determine HOME")?;
    let target_dir = PathBuf::from(home).join(".morphvpn");
    fs::create_dir_all(&target_dir)?;

    println!("");
    println!("Config directory: {}", target_dir.display());

    println!("Generating client keys...");
    let x25519_identity = crate::identity::generate_x25519_identity();
    let key_path = target_dir.join("client.key");
    let pub_path = target_dir.join("client.pub");
    crate::identity::write_private_key_file(&key_path, &x25519_identity.private)?;
    crate::identity::write_public_key_file(&pub_path, &x25519_identity.public)?;
    set_permissions(&key_path)?;

    println!("  Private key: {}", key_path.display());
    println!("  Public key:  {}", pub_path.display());

    let psk_path = target_dir.join("client.psk");
    fs::write(&psk_path, format!("{}\n", psk_hex))?;
    set_permissions(&psk_path)?;

    let config_path = target_dir.join("client.toml");
    let config_content = format!(
        r#"# MorphVPN Client Configuration
# Generated by morphvpn setup

[client]
server = "{}"
private_key = "{}"
server_public_key = "{}"
tun = "{}"
tun_ip = "{}"
gateway = "{}"

[client.psk]
file = "{}"

[client.tcp]
enabled = true

[client.keepalive]
interval_secs = 15
timeout_secs = 45

[log]
format = "pretty"
level = "morphvpn=info"
"#,
        server_addr,
        key_path.display(),
        server_pub_key,
        tun,
        tun_ip,
        gateway,
        psk_path.display(),
    );
    fs::write(&config_path, config_content)?;
    println!("  Config:      {}", config_path.display());

    println!("");
    println!("=== Setup Complete ===");
    println!("");
    println!("Client public key (add to server's ACL):");
    println!("  {}", hex::encode(x25519_identity.public));
    println!("  Inner IP: {}", tun_ip);
    println!("");
    println!("To connect:");
    println!("  morphvpn --config {} client", config_path.display());
    println!("");

    Ok(())
}

fn generate_random_hex(bytes: usize) -> String {
    use rand::RngCore;
    let mut key = vec![0u8; bytes];
    rand::rngs::OsRng.fill_bytes(&mut key);
    hex::encode(key)
}

#[allow(unused_variables)]
fn set_permissions(path: &Path) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    }
    Ok(())
}

fn run_cmd_quiet(program: &str, args: &[&str]) -> Result<()> {
    let _output = std::process::Command::new(program)
        .args(args)
        .output()?;
    Ok(())
}

fn bind_port(addr: &str) -> u16 {
    addr.rsplit(':').next().and_then(|p| p.parse().ok()).unwrap_or(51820)
}
